services:
  - type: web
    name: adi-token-health-api
    runtime: python
    region: frankfurt
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: COINMARKETCAP_API_KEY
        sync: false
      - key: KRAKEN_API_KEY
        sync: false
      - key: KRAKEN_API_SECRET
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"
